# Lesson 1 Practice: NumPy Part 1
Use this notebook to follow along with the lesson in the corresponding lesson notebook: [L01-Numpy_Part1-Lesson.ipynb](./L01-Numpy_Part1-Lesson.ipynb).  



## Instructions
Follow along with the teaching material in the lesson. Throughout the tutorial sections labeled as "Tasks" are interspersed and indicated with the icon: ![Task](http://icons.iconarchive.com/icons/sbstnblnd/plateau/16/Apps-gnome-info-icon.png). You should follow the instructions provided in these sections by performing them in the practice notebook.  When the tutorial is completed you can turn in the final practice notebook. For each task, use the cell below it to write and test your code.  You may add additional cells for any task as needed or desired.  

## Task 1a: Setup

In the practice notebook, import the following packages:
+ `numpy` as `np`

In [1]:
import numpy as np

## Task 2a: Creating Arrays

In the practice notebook, perform the following.  
- Create a 1-dimensional numpy array and print it.
- Create a 2-dimensional numpy array and print it.
- Create a 3-dimensional numpy array and print it.

In [4]:
arr = np.array([1,2,3])
arr2 = np.array([[0,0,0], [1,1,1]])
arr3 = np.array([[[0,0],[1,1]],[[2,2],[3,3]]])

#my_3d_array = np.array([[[1,2,3,4], [5,6,7,8]], [[1,2,3,4], [9,10,11,12]]])

print(arr)
print(arr2)
print(arr3)

#print(my_3d_array)

[1 2 3]
[[0 0 0]
 [1 1 1]]
[[[0 0]
  [1 1]]

 [[2 2]
  [3 3]]]
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 1  2  3  4]
  [ 9 10 11 12]]]


## Task 3a: Accessing Array Attributes

In the practice notebook, perform the following.

- Create a NumPy array.
- Write code that prints these attributes (one per line): `ndim`, `shape`, `size`, `dtype`, `itemsize`, `data`, `nbytes`.
- Add a comment line, before each line describing what value the attribute returns. 


In [6]:
a = np.array([1,2,3,4])

print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(a.data)
print(a.nbytes)

1
(4,)
4
int32
4
16


## Task 4a: Initializing Arrays

In the practice notebook, perform the following.

+ Create an initialized array by using these functions:  `ones`, `zeros`, `empty`, `full`, `arange`, `linspace` and `random.random`. Be sure to follow each array creation with a call to `print()` to display your newly created arrays. 
+ Add a comment above each function call describing what is being done.  

In [16]:
a_ones = np.ones((2, ))
print(a_ones)

a_zeros = np.zeros((4,))
print(a_zeros)

print(np.empty((4,)))
print(np.full((4,), fill_value = 2))
print(np.arange(3,7))
print(np.linspace(1,30))

[1. 1.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[2 2 2 2]
[3 4 5 6]
[ 1.          1.59183673  2.18367347  2.7755102   3.36734694  3.95918367
  4.55102041  5.14285714  5.73469388  6.32653061  6.91836735  7.51020408
  8.10204082  8.69387755  9.28571429  9.87755102 10.46938776 11.06122449
 11.65306122 12.24489796 12.83673469 13.42857143 14.02040816 14.6122449
 15.20408163 15.79591837 16.3877551  16.97959184 17.57142857 18.16326531
 18.75510204 19.34693878 19.93877551 20.53061224 21.12244898 21.71428571
 22.30612245 22.89795918 23.48979592 24.08163265 24.67346939 25.26530612
 25.85714286 26.44897959 27.04081633 27.63265306 28.2244898  28.81632653
 29.40816327 30.        ]


## Task 5a:  Broadcasting Arrays

In the practice notebook, perform the following.

+ Create two arrays of differing sizes but compatible with broadcasting.
+ Perform addition, multiplication and subtraction.
+ Create two additional arrays of differing size that do not meet the rules for broadcasting and try a mathematical operation.  

In [20]:
a = np.array((3,4))
b = np.array((3,1))

aplusb = a + b
print(aplusb)

amultb = a * b
print(amultb)

asubb = a - b
print(asubb)


[6 5]
[9 4]
[0 3]


## Task 6a: Math/Stats Aggregate Functions

In the practice notebook, perform the following.

+ Create three to five arrays
+ Experiment with each of the aggregation functions: `sum`, `minimum`, `maximum`, `cumsum`, `mean`, `np.corrcoef`, `np.std`, `np.var`. 
+ For each function call, add a comment line above it that describes what it does.  
```


In [34]:
a = np.zeros((5,))
b = np.array((5,5,5,1,1))
c = np.array((1,2,3,4,5))
d = np.ones((3,4))

print(np.sum(b))
print(np.minimum(b,c))
print(np.maximum(c,b))
print(np.mean(c))
print(np.corrcoef(c))
print(np.std(c))
print(np.var(c))

17
[1 2 3 1 1]
[5 5 5 4 5]
3.0
1.0
1.4142135623730951
2.0


## Task 6b: Logical Aggregate Functions

In the practice notebook, perform the following.

+ Create two arrays containing boolean values.
+ Experiment with each of the aggregation functions: `logical_and`, `logical_or`, `logical_not`. 
+ For each function call, add a comment line above it that describes what it does.  
```

In [36]:
a = np.array((True, True, False, True))
b = np.array((False, True, False, False))

print(np.logical_and(a,b))
print(np.logical_or(a,b))
print(np.logical_not(a,b))

[False  True False False]
[ True  True False  True]
[False False  True False]
